nota1 = float(input())
nota2 = float(input())
nota3 = float(input())
peso1 = 2
peso2 = 3
peso3 = 5
somadospesos = 10
MEDIA = ((nota1 * peso1) + (nota2 * peso2) + (nota3 * peso3)) / (somadospesos)
print("MEDIA = %.1f" % MEDIA)
