codigo1, numero1, preco1 = input().split()
codigo2, numero2, preco2 = input().split()
codigo1 = int(codigo1)
numero1 = int(numero1)
preco1 = float(preco1)
codigo2 = int(codigo2)
numero2 = int(numero2)
preco2 = float(preco2)
TOTAL = (numero1 * preco1) + (numero2 * preco2)
print("VALOR A PAGAR: R$ %.2f" % TOTAL)
